language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

# services:
#   - postgresql

# before-script:
#   -psql -c 'create database jamii_businesstest;' -U postgres

script:
  - nosetests

# notifications:
#   email:
#     recipients:
#       - bochiegfx@gmail.com
#     on_success: always # default: change
#     on_failure: always # default: always
